name: Alpha Update

on:
  workflow_dispatch:

jobs:
    update:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run alpha update
        run: |
          kubebuilder alpha update --force

      - name: Check commit history
        run: |
          git status
          git log --all --oneline

      - name: Check for changes and create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the merge branch created by alpha update
          PR_BRANCH=$(git branch --show-current)
          git push origin "$PR_BRANCH"

          # Create PR
          gh pr create \
            --title "chore: update Kubebuilder scaffolding" \
            --body "Automated update of Kubebuilder project scaffolding to latest version." \
            --base main \
            --head "$PR_BRANCH"